/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models.view

// If you need to make any changes to this list note the list is also defined in javascript and also needs to be changed there
object CivilServantDepartments {
  val departments = Seq(
    "Accountant in Bankruptcy",
    "Advisory, Conciliation and Arbitration Service",
    "Animal and Plant Health Agency",
    "Attorney General's Office",
    "Building Digital UK",
    "Cabinet Office",
    "Centre for Environment, Fisheries and Aquaculture Science",
    "Charity Commission",
    "Companies House",
    "Competition and Markets Authority",
    "Criminal Injuries Compensation Authority",
    "Crown Commercial Service",
    "Crown Office and Procurator Fiscal Service",
    "Crown Prosecution Service",
    "Defence Electronics and Components Agency",
    "Defence Equipment and Support",
    "Defence Science and Technology Laboratory",
    "Department for Business and Trade",
    "Department for Culture, Media and Sport",
    "Department for Education",
    "Department for Energy Security and Net Zero",
    "Department for Environment, Food and Rural Affairs",
    "Department for Levelling Up, Housing and Communities",
    "Department for Science, Innovation and Technology",
    "Department for Transport",
    "Department for Work and Pensions",
    "Department of Health and Social Care",
    "Disclosure Scotland",
    "Driver and Vehicle Licensing Agency",
    "Driver and Vehicle Standards Agency",
    "Education and Skills Funding Agency",
    "Education Scotland",
    "Estyn",
    "FCDO Services",
    "Food Standards Agency",
    "Food Standards Scotland",
    "Foreign, Commonwealth and Development Office",
    "Forestry and Land Scotland",
    "Government Actuary's Department",
    "Government Internal Audit Agency",
    "Government Legal Department",
    "Government Property Agency",
    "Health and Safety Executive",
    "HM Courts and Tribunals Service",
    "HM Crown Prosecution Service Inspectorate",
    "HM Land Registry",
    "HM Prison and Probation Service",
    "HM Revenue and Customs",
    "HM Treasury",
    "Home Office",
    "Institute for Apprenticeships and Technical Education",
    "Intellectual Property Office",
    "Legal Aid Agency",
    "Maritime and Coastguard Agency",
    "Medicines and Healthcare Products Regulatory Agency",
    "Met Office",
    "Ministry of Defence",
    "Ministry of Justice",
    "National Crime Agency",
    "National Infrastructure Commission",
    "National Records of Scotland",
    "National Savings and Investments",
    "Northern Ireland Office",
    "Office for Budget Responsibility",
    "Office for Standards in Education, Children's Services and Skills",
    "Office of Gas and Electricity Markets",
    "Office of Qualifications and Examinations Regulation",
    "Office of Rail and Road",
    "Office of the Public Guardian",
    "Office of the Scottish Charity Regulator",
    "Office of the Secretary of State for Scotland",
    "Office of the Secretary of State for Wales",
    "Planning Inspectorate",
    "Queen Elizabeth II Centre",
    "Registers of Scotland",
    "Revenue Scotland",
    "Royal Fleet Auxiliary",
    "Rural Payments Agency",
    "Scottish Courts and Tribunals Service",
    "Scottish Forestry",
    "Scottish Government",
    "Scottish Housing Regulator",
    "Scottish Prison Service",
    "Scottish Public Pensions Agency",
    "Serious Fraud Office",
    "Social Security Scotland",
    "Student Awards Agency for Scotland",
    "Submarine Delivery Agency",
    "Teaching Regulation Agency",
    "The Insolvency Service",
    "The National Archives",
    "Transport Scotland",
    "UK Debt Management Office",
    "UK Export Finance",
    "UK Health Security Agency",
    "UK Hydrographic Office",
    "UK Space Agency",
    "UK Statistics Authority",
    "UK Supreme Court",
    "Valuation Office Agency",
    "Vehicle Certification Agency",
    "Veterinary Medicines Directorate",
    "Water Services Regulation Authority",
    "Welsh Government",
    "Welsh Revenue Authority",
    "Wilton Park"
  )
}
